name: Lint & Test
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with: 
          distribution: 'adopt'
          java-version: '11'
      - uses: android-actions/setup-android@v2
      - run: ./gradlew lint
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with: 
          distribution: 'adopt'
          java-version: '11'
      - uses: android-actions/setup-android@v2
      - name: Run Tests
        run: ./gradlew test

