name: Pull Request Checks
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint 
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: 18

      - uses: android-actions/setup-android@v3

      - run: ./gradlew lint

      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: "**/build/reports/lint-*.xml" # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-android-lint exit 1.

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18

      - uses: android-actions/setup-android@v3

      - name: Run Tests
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test*/TEST-*.xml'

