name: Release Ortto Android-SDK

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: ${{ github.ref }}

    strategy:
      matrix:
        include:
          - environment: PROD
            command: "publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository"

    environment:
      name: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Extract Version Tag
        run: |
          echo "VERSION_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - uses: android-actions/setup-android@v2

      - name: Run Tests
        run: ./gradlew test

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Bundle
        env:
          VERSION_NAME: ${{ env.VERSION_NAME }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run:
          ./gradlew ${{ matrix.command }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_NAME }}
          release_name: Release ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false

